spring:
  datasource:
    url: jdbc:mysql://localhost/ckdxc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #    url: jdbc:mysql://47.106.90.18:3306/ckdxc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  redis:
    database: 0
    host: 47.106.90.18
    port: 6379
    timeout: 10000
    #    password: "sch123"
    jedis:
      pool:
        max: -1
        min-idle: 0
        max-wait: 5000
        max-idle: -1
  thymeleaf:
    mode: HTML # 用非严格的 HTML
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
    cache: false # 开发时关闭缓存,不然没法看到实时页面



# 接口地址
index:
  x-web-interface-search-default: https://api.bilibili.com/x/web-interface/search/default                               # 主页--搜索栏
  index-recommend: https://www.bilibili.com/index/recommend.json                                                        # 主页--推荐
  room-v1-RoomRecommend-biliIndexRecList: https://api.live.bilibili.com/room/v1/RoomRecommend/biliIndexRecList          # 主页--直播推荐
  pgc-web-timeline: https://api.bilibili.com/pgc/web/timeline?types=1                                                   # 主页--番剧列表
  #『连载动画』投稿在 2019年05月24日 - 2019年05月27日 的数据综合得分，每日更新一次
  pgc-web-rank-list: https://api.bilibili.com/pgc/web/rank/list?season_type=1&day=3

  # rid:  33连载动画, 32完结动画, 51资讯视频, 152官方延伸, 153国产动画, 168国产原创相关, 169布袋戏, 195动态漫・广播剧
  # day:  3就是3天,7就是一周      original:  0排行榜 不带这个参数 就是随机
anime:
  api-timeline_v2_global: https://bangumi.bilibili.com/api/timeline_v2_global                                           # 动画区--最近更新
  x-web-interface-dynamic-region-33: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=33               # 动画区--连载动画
  x-web-interface-ranking-region: https://api.bilibili.com/x/web-interface/ranking/region?rid=33&day=3&original=0       # 动画区--连载动画--热门
  x-web-interface-dynamic-region-32: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=32               # 动画区--完结动画
  x-web-interface-dynamic-region-32-0: https://api.bilibili.com/x/web-interface/ranking/region?rid=32&day=3&original=0  # 动画区--完结动画--热门
  x-web-interface-dynamic-region-51: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=51               # 动画区--资讯视频
  x-web-interface-dynamic-region-51-0: https://api.bilibili.com/x/web-interface/ranking/region?rid=51&day=3&original=0  # 动画区--资讯视频--热门
  x-web-interface-dynamic-region-152: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=152             # 动画区--官方延伸
  x-web-interface-dynamic-region-152-0: https://api.bilibili.com/x/web-interface/ranking/region?rid=152&day=3&original=0 #动画区--官方延伸--热门
china:
  api-timeline_v2_cn: https://bangumi.bilibili.com/api/timeline_v2_cn                                                   # 国创区--最近更新
  x-web-interface-dynamic-region-153: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=153             # 国创区--国产动画
  x-web-interface-ranking-region: https://api.bilibili.com/x/web-interface/ranking/region?rid=153&day=3&original=0      # 国创区--国产动画--热门
  x-web-interface-dynamic-region-168: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=168             # 国创区--国产原创相关
  x-web-interface-dynamic-region-168-0: https://api.bilibili.com/x/web-interface/ranking/region?rid=168&day=3&original=0 #国创区--国产原创相关--热门
  x-web-interface-dynamic-region-169: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=169             # 国创区--布袋戏
  x-web-interface-dynamic-region-169-0: https://api.bilibili.com/x/web-interface/ranking/region?rid=169&day=3&original=0 #国创区--布袋戏--热门
  x-web-interface-dynamic-region-195: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=195             # 国创区--动态漫・广播剧
  x-web-interface-dynamic-region-195-0: https://api.bilibili.com/x/web-interface/ranking/region?rid=195&day=3&original=0 #国创区--动态漫・广播剧--热门
  x-web-interface-dynamic-region-170: https://api.bilibili.com/x/web-interface/dynamic/region?ps=15&rid=170             # 国创区--资讯
  x-web-interface-dynamic-region-170-0: https://api.bilibili.com/x/web-interface/ranking/region?rid=170&day=3&original=0 #国创区--资讯--热门
music:
